// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapacket.proto

package uk.ac.ox.cs.camerastreamer.packet;

public final class DataPacket {
  private DataPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 timestamp = 1;
    boolean hasTimestamp();
    long getTimestamp();
    
    // optional float acc0 = 2;
    boolean hasAcc0();
    float getAcc0();
    
    // optional float acc1 = 3;
    boolean hasAcc1();
    float getAcc1();
    
    // optional float acc2 = 4;
    boolean hasAcc2();
    float getAcc2();
    
    // optional double longitude = 5;
    boolean hasLongitude();
    double getLongitude();
    
    // optional double latitude = 6;
    boolean hasLatitude();
    double getLatitude();
    
    // repeated .camerastreamer.PointData feature = 7;
    java.util.List<uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData> 
        getFeatureList();
    uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData getFeature(int index);
    int getFeatureCount();
    java.util.List<? extends uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointDataOrBuilder> 
        getFeatureOrBuilderList();
    uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointDataOrBuilder getFeatureOrBuilder(
        int index);
  }
  public static final class Header extends
      com.google.protobuf.GeneratedMessage
      implements HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(Builder builder) {
      super(builder);
    }
    private Header(boolean noInit) {}
    
    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }
    
    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.ox.cs.camerastreamer.packet.DataPacket.internal_static_camerastreamer_Header_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.ox.cs.camerastreamer.packet.DataPacket.internal_static_camerastreamer_Header_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // optional float acc0 = 2;
    public static final int ACC0_FIELD_NUMBER = 2;
    private float acc0_;
    public boolean hasAcc0() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getAcc0() {
      return acc0_;
    }
    
    // optional float acc1 = 3;
    public static final int ACC1_FIELD_NUMBER = 3;
    private float acc1_;
    public boolean hasAcc1() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getAcc1() {
      return acc1_;
    }
    
    // optional float acc2 = 4;
    public static final int ACC2_FIELD_NUMBER = 4;
    private float acc2_;
    public boolean hasAcc2() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getAcc2() {
      return acc2_;
    }
    
    // optional double longitude = 5;
    public static final int LONGITUDE_FIELD_NUMBER = 5;
    private double longitude_;
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public double getLongitude() {
      return longitude_;
    }
    
    // optional double latitude = 6;
    public static final int LATITUDE_FIELD_NUMBER = 6;
    private double latitude_;
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public double getLatitude() {
      return latitude_;
    }
    
    // repeated .camerastreamer.PointData feature = 7;
    public static final int FEATURE_FIELD_NUMBER = 7;
    private java.util.List<uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData> feature_;
    public java.util.List<uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData> getFeatureList() {
      return feature_;
    }
    public java.util.List<? extends uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointDataOrBuilder> 
        getFeatureOrBuilderList() {
      return feature_;
    }
    public int getFeatureCount() {
      return feature_.size();
    }
    public uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData getFeature(int index) {
      return feature_.get(index);
    }
    public uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointDataOrBuilder getFeatureOrBuilder(
        int index) {
      return feature_.get(index);
    }
    
    private void initFields() {
      timestamp_ = 0L;
      acc0_ = 0F;
      acc1_ = 0F;
      acc2_ = 0F;
      longitude_ = 0D;
      latitude_ = 0D;
      feature_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getFeatureCount(); i++) {
        if (!getFeature(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, acc0_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, acc1_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, acc2_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, longitude_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, latitude_);
      }
      for (int i = 0; i < feature_.size(); i++) {
        output.writeMessage(7, feature_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, acc0_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, acc1_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, acc2_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, longitude_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, latitude_);
      }
      for (int i = 0; i < feature_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, feature_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements uk.ac.ox.cs.camerastreamer.packet.DataPacket.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.ac.ox.cs.camerastreamer.packet.DataPacket.internal_static_camerastreamer_Header_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.ac.ox.cs.camerastreamer.packet.DataPacket.internal_static_camerastreamer_Header_fieldAccessorTable;
      }
      
      // Construct using uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFeatureFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        acc0_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        acc1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        acc2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (featureBuilder_ == null) {
          feature_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          featureBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header.getDescriptor();
      }
      
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header getDefaultInstanceForType() {
        return uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header.getDefaultInstance();
      }
      
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header build() {
        uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header buildPartial() {
        uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header result = new uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.acc0_ = acc0_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.acc1_ = acc1_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.acc2_ = acc2_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.latitude_ = latitude_;
        if (featureBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            feature_ = java.util.Collections.unmodifiableList(feature_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.feature_ = feature_;
        } else {
          result.feature_ = featureBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header) {
          return mergeFrom((uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header other) {
        if (other == uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasAcc0()) {
          setAcc0(other.getAcc0());
        }
        if (other.hasAcc1()) {
          setAcc1(other.getAcc1());
        }
        if (other.hasAcc2()) {
          setAcc2(other.getAcc2());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (featureBuilder_ == null) {
          if (!other.feature_.isEmpty()) {
            if (feature_.isEmpty()) {
              feature_ = other.feature_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureFeatureIsMutable();
              feature_.addAll(other.feature_);
            }
            onChanged();
          }
        } else {
          if (!other.feature_.isEmpty()) {
            if (featureBuilder_.isEmpty()) {
              featureBuilder_.dispose();
              featureBuilder_ = null;
              feature_ = other.feature_;
              bitField0_ = (bitField0_ & ~0x00000040);
              featureBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFeatureFieldBuilder() : null;
            } else {
              featureBuilder_.addAllMessages(other.feature_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getFeatureCount(); i++) {
          if (!getFeature(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              acc0_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              acc1_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              acc2_ = input.readFloat();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              longitude_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              latitude_ = input.readDouble();
              break;
            }
            case 58: {
              uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder subBuilder = uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFeature(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 timestamp = 1;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // optional float acc0 = 2;
      private float acc0_ ;
      public boolean hasAcc0() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getAcc0() {
        return acc0_;
      }
      public Builder setAcc0(float value) {
        bitField0_ |= 0x00000002;
        acc0_ = value;
        onChanged();
        return this;
      }
      public Builder clearAcc0() {
        bitField0_ = (bitField0_ & ~0x00000002);
        acc0_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float acc1 = 3;
      private float acc1_ ;
      public boolean hasAcc1() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getAcc1() {
        return acc1_;
      }
      public Builder setAcc1(float value) {
        bitField0_ |= 0x00000004;
        acc1_ = value;
        onChanged();
        return this;
      }
      public Builder clearAcc1() {
        bitField0_ = (bitField0_ & ~0x00000004);
        acc1_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float acc2 = 4;
      private float acc2_ ;
      public boolean hasAcc2() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getAcc2() {
        return acc2_;
      }
      public Builder setAcc2(float value) {
        bitField0_ |= 0x00000008;
        acc2_ = value;
        onChanged();
        return this;
      }
      public Builder clearAcc2() {
        bitField0_ = (bitField0_ & ~0x00000008);
        acc2_ = 0F;
        onChanged();
        return this;
      }
      
      // optional double longitude = 5;
      private double longitude_ ;
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public double getLongitude() {
        return longitude_;
      }
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000010;
        longitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000010);
        longitude_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double latitude = 6;
      private double latitude_ ;
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public double getLatitude() {
        return latitude_;
      }
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000020;
        latitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000020);
        latitude_ = 0D;
        onChanged();
        return this;
      }
      
      // repeated .camerastreamer.PointData feature = 7;
      private java.util.List<uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData> feature_ =
        java.util.Collections.emptyList();
      private void ensureFeatureIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          feature_ = new java.util.ArrayList<uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData>(feature_);
          bitField0_ |= 0x00000040;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointDataOrBuilder> featureBuilder_;
      
      public java.util.List<uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData> getFeatureList() {
        if (featureBuilder_ == null) {
          return java.util.Collections.unmodifiableList(feature_);
        } else {
          return featureBuilder_.getMessageList();
        }
      }
      public int getFeatureCount() {
        if (featureBuilder_ == null) {
          return feature_.size();
        } else {
          return featureBuilder_.getCount();
        }
      }
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData getFeature(int index) {
        if (featureBuilder_ == null) {
          return feature_.get(index);
        } else {
          return featureBuilder_.getMessage(index);
        }
      }
      public Builder setFeature(
          int index, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData value) {
        if (featureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureIsMutable();
          feature_.set(index, value);
          onChanged();
        } else {
          featureBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFeature(
          int index, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder builderForValue) {
        if (featureBuilder_ == null) {
          ensureFeatureIsMutable();
          feature_.set(index, builderForValue.build());
          onChanged();
        } else {
          featureBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFeature(uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData value) {
        if (featureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureIsMutable();
          feature_.add(value);
          onChanged();
        } else {
          featureBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFeature(
          int index, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData value) {
        if (featureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureIsMutable();
          feature_.add(index, value);
          onChanged();
        } else {
          featureBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFeature(
          uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder builderForValue) {
        if (featureBuilder_ == null) {
          ensureFeatureIsMutable();
          feature_.add(builderForValue.build());
          onChanged();
        } else {
          featureBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFeature(
          int index, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder builderForValue) {
        if (featureBuilder_ == null) {
          ensureFeatureIsMutable();
          feature_.add(index, builderForValue.build());
          onChanged();
        } else {
          featureBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFeature(
          java.lang.Iterable<? extends uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData> values) {
        if (featureBuilder_ == null) {
          ensureFeatureIsMutable();
          super.addAll(values, feature_);
          onChanged();
        } else {
          featureBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFeature() {
        if (featureBuilder_ == null) {
          feature_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          featureBuilder_.clear();
        }
        return this;
      }
      public Builder removeFeature(int index) {
        if (featureBuilder_ == null) {
          ensureFeatureIsMutable();
          feature_.remove(index);
          onChanged();
        } else {
          featureBuilder_.remove(index);
        }
        return this;
      }
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder getFeatureBuilder(
          int index) {
        return getFeatureFieldBuilder().getBuilder(index);
      }
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointDataOrBuilder getFeatureOrBuilder(
          int index) {
        if (featureBuilder_ == null) {
          return feature_.get(index);  } else {
          return featureBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointDataOrBuilder> 
           getFeatureOrBuilderList() {
        if (featureBuilder_ != null) {
          return featureBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(feature_);
        }
      }
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder addFeatureBuilder() {
        return getFeatureFieldBuilder().addBuilder(
            uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.getDefaultInstance());
      }
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder addFeatureBuilder(
          int index) {
        return getFeatureFieldBuilder().addBuilder(
            index, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.getDefaultInstance());
      }
      public java.util.List<uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder> 
           getFeatureBuilderList() {
        return getFeatureFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointDataOrBuilder> 
          getFeatureFieldBuilder() {
        if (featureBuilder_ == null) {
          featureBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder, uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointDataOrBuilder>(
                  feature_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          feature_ = null;
        }
        return featureBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:camerastreamer.Header)
    }
    
    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:camerastreamer.Header)
  }
  
  public interface PointDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required double x = 8;
    boolean hasX();
    double getX();
    
    // required double y = 9;
    boolean hasY();
    double getY();
  }
  public static final class PointData extends
      com.google.protobuf.GeneratedMessage
      implements PointDataOrBuilder {
    // Use PointData.newBuilder() to construct.
    private PointData(Builder builder) {
      super(builder);
    }
    private PointData(boolean noInit) {}
    
    private static final PointData defaultInstance;
    public static PointData getDefaultInstance() {
      return defaultInstance;
    }
    
    public PointData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.ox.cs.camerastreamer.packet.DataPacket.internal_static_camerastreamer_PointData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.ox.cs.camerastreamer.packet.DataPacket.internal_static_camerastreamer_PointData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required double x = 8;
    public static final int X_FIELD_NUMBER = 8;
    private double x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public double getX() {
      return x_;
    }
    
    // required double y = 9;
    public static final int Y_FIELD_NUMBER = 9;
    private double y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getY() {
      return y_;
    }
    
    private void initFields() {
      x_ = 0D;
      y_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(8, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(9, y_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.ac.ox.cs.camerastreamer.packet.DataPacket.internal_static_camerastreamer_PointData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.ac.ox.cs.camerastreamer.packet.DataPacket.internal_static_camerastreamer_PointData_fieldAccessorTable;
      }
      
      // Construct using uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.getDescriptor();
      }
      
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData getDefaultInstanceForType() {
        return uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.getDefaultInstance();
      }
      
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData build() {
        uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData buildPartial() {
        uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData result = new uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData) {
          return mergeFrom((uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData other) {
        if (other == uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 65: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required double x = 8;
      private double x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getX() {
        return x_;
      }
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }
      
      // required double y = 9;
      private double y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getY() {
        return y_;
      }
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:camerastreamer.PointData)
    }
    
    static {
      defaultInstance = new PointData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:camerastreamer.PointData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_camerastreamer_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_camerastreamer_Header_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_camerastreamer_PointData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_camerastreamer_PointData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020datapacket.proto\022\016camerastreamer\"\226\001\n\006H" +
      "eader\022\021\n\ttimestamp\030\001 \001(\003\022\014\n\004acc0\030\002 \001(\002\022\014" +
      "\n\004acc1\030\003 \001(\002\022\014\n\004acc2\030\004 \001(\002\022\021\n\tlongitude\030" +
      "\005 \001(\001\022\020\n\010latitude\030\006 \001(\001\022*\n\007feature\030\007 \003(\013" +
      "2\031.camerastreamer.PointData\"!\n\tPointData" +
      "\022\t\n\001x\030\010 \002(\001\022\t\n\001y\030\t \002(\001B/\n!uk.ac.ox.cs.ca" +
      "merastreamer.packetB\nDataPacket"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_camerastreamer_Header_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_camerastreamer_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_camerastreamer_Header_descriptor,
              new java.lang.String[] { "Timestamp", "Acc0", "Acc1", "Acc2", "Longitude", "Latitude", "Feature", },
              uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header.class,
              uk.ac.ox.cs.camerastreamer.packet.DataPacket.Header.Builder.class);
          internal_static_camerastreamer_PointData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_camerastreamer_PointData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_camerastreamer_PointData_descriptor,
              new java.lang.String[] { "X", "Y", },
              uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.class,
              uk.ac.ox.cs.camerastreamer.packet.DataPacket.PointData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
